name: 📖 User Story (BDD)
description: This is the core unit of work for developers.
title: '[Story] <title>'
labels: story
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Description
        As a [role], I want [feature] so that [reason].
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: List clear, testable criteria for story completion.
      placeholder: 'List acceptance criteria...'
  - type: textarea
    id: related
    attributes:
      label: Related Epics/Features/Tasks
      description: Link related epics, features, or tasks (use issue numbers, e.g. #123).
      placeholder: 'List related issues...'
  - type: textarea
    id: stakeholders
    attributes:
      label: Stakeholders
      description: List key stakeholders and their roles.
      placeholder: 'List stakeholders...'
  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any other relevant information.
      placeholder: 'Add notes...'
