name: CI
on:
  push:
    branches: [main, developer]
  pull_request:
    branches: [main, developer]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint || echo "No lint script defined"
      - name: Test
        run: npm test || echo "No test script defined"
      - name: Build
        run: npm run build || echo "No build script defined"
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
